server:
  port: 8088

spring:
  application:
    name: bids-service

  datasource:
    url: jdbc:postgresql://localhost:5432/Bids
    username: postgres
    password: A123@123h
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka/