server:
  port: 8082

spring:
  application:
    name: auction-service

  datasource:
    url: jdbc:postgresql://db_auction:5432/Auction
    username: postgres
    password: A123@123h
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://dicovery-service:8761/eureka/